---
abstract: 'Defines a JSON format to represent SQL queries which can be validated and then used to generate SQL syntax.'
author:
  - 'Chris Hoefler <bhoefler@draper.com>'
build_requires:
  Test::More: '0'
  diagnostics: '0'
  perl: '5.014'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.014'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JsonSQL
requires:
  Class::Load: '0'
  Data::Dumper: '0'
  JSON::Parse: '0'
  JSON::Validator: '0'
  List::Util: '0'
  SQL::Maker::Select: '0'
  SQL::QueryMaker: '0'
  base: '0'
  perl: '5.014'
  strict: '0'
  warnings: '0'
version: '0.4'
x_serialization_backend: 'YAML::Tiny version 1.69'
